library(shiny)

shinyUI(pageWithSidebar(
  headerPanel(
    h1(class="well",align="center","Predicting Predominant Forest Cover of Roosevelt National Forest, Northern Colorado"), 
    "Predicting Forest Cover"
  ),
  sidebarPanel(
    h3("Topography:"),
    numericInput("elevation","Elevation(in meters):",0,min=0,max=4000,step=100),
    numericInput("aspect","Aspect(degrees azimuth):",0,min=0,max=360,step=1),
    numericInput("slope","Slope(Slope in degrees):",0,min=0,max=60,step=1),
    numericInput("horiz_dist_hydr","Horizontal Distance To Hydrology(in meters):",0,min=0,max=1500,step=50),
    numericInput("vert_dist_hydr","Vertical Distance To Hydrology(in meters):",0,min=0,max=1000,step=50),
    numericInput("horiz_dist_road","Horizontal Distance To Roadways(in meters):",0,min=0,max=10000,step=100),
    numericInput("hill_shade_9","Hillshade at 9am of Summer Solstice(0 to 255):",0,min=0,max=255,step=5),
    numericInput("hill_shade_noon","Hillshade at noon of Summer Solstice(0 to 255):",0,min=0,max=255,step=5),
    numericInput("hill_shade_3","Hillshade at 3pm of Summer Solstice(0 to 255):",0,min=0,max=255,step=5),
    numericInput("horiz_dist_fire","Horizontal Distance To Wildfire Ignition Points(in meters):",0,min=0,max=10000,step=100),
    selectInput("wilderness","Wilderness Area:",c(
                               "01-Rawah Wilderness Area",
                               "02-Neota Wilderness Area2",
                               "03-Comanche Peak Wilderness Area",
                               "04-Cache la Poudre Wilderness Area")),  
    selectInput("soil_type","Soil Type:",c("01-Cathedral family - Rock outcrop complex, extremely stony",
                                           "02-Vanet - Ratake families complex, very stony",
                                           "03-Haploborolis - Rock outcrop complex, rubbly",
                                           "04-Ratake family - Rock outcrop complex, rubbly",
                                           "05-Vanet family - Rock outcrop complex complex, rubbly",
                                           "06-Vanet - Wetmore families - Rock outcrop complex, stony",
                                           "07-Gothic family",
                                           "08-Supervisor - Limber families complex",
                                           "09-Troutville family, very stony",
                                           "10-Bullwark - Catamount families - Rock outcrop complex, rubbly",
                                           "11-Bullwark - Catamount families - Rock land complex, rubbly",
                                           "12-Legault family - Rock land complex, stony",
                                           "13-Catamount family - Rock land - Bullwark family complex, rubbly",
                                           "14-Pachic Argiborolis - Aquolis complex",
                                           "15-unspecified in the USFS Soil and ELU Survey",
                                           "16-Cryaquolis - Cryoborolis complex",
                                           "17-Gateview family - Cryaquolis complex",
                                           "18-Rogert family, very stony",
                                           "19-Typic Cryaquolis - Borohemists complex",
                                           "20-Typic Cryaquepts - Typic Cryaquolls complex",
                                           "21-Typic Cryaquolls - Leighcan family, till substratum complex",
                                           "22-Leighcan family, till substratum, extremely bouldery",
                                           "23-Leighcan family, till substratum - Typic Cryaquolls complex",
                                           "24-Leighcan family, extremely stony",
                                           "25-Leighcan family, warm, extremely stony",
                                           "26-Granile - Catamount families complex, very stony",
                                           "27-Leighcan family, warm - Rock outcrop complex, extremely stony",
                                           "28-Leighcan family - Rock outcrop complex, extremely stony",
                                           "29-Como - Legault families complex, extremely stony",
                                           "30-Como family - Rock land - Legault family complex, extremely stony",
                                           "31-Leighcan - Catamount families complex, extremely stony",
                                           "32-Catamount family - Rock outcrop - Leighcan family complex, extremely stony",
                                           "33-Leighcan - Catamount families - Rock outcrop complex, extremely stony",
                                           "34-Cryorthents - Rock land complex, extremely stony",
                                           "35-Cryumbrepts - Rock outcrop - Cryaquepts complex",
                                           "36-Bross family - Rock land - Cryumbrepts complex, extremely stony",
                                           "37-Rock outcrop - Cryumbrepts - Cryorthents complex, extremely stony",
                                           "38-Leighcan - Moran families - Cryaquolls complex, extremely stony",
                                           "39-Moran family - Cryorthents - Leighcan family complex, extremely stony",
                                           "40-Moran family - Cryorthents - Rock land complex, extremely stony")),
      submitButton("Submit")  
    
  ),  
  mainPanel(
    h4("This application predicts the forest cover type of a wilderness area in the Roosevelt National Park, northern Colorado.It is a prediction using Cartographic Variables (not based on satelite imagery) and is based on the parameters that you select in \"Input Values\" section in the left side panel."),
    h4("Simply enter the values that describes the topography and click Submit button to get the prediction."),
    tag("hr",varArgs = ""),
    h4("You entered:"),
    uiOutput("elevationText"),
    uiOutput("aspectText"),
    uiOutput("slopeText"),
    uiOutput("horiz_dist_hydrText"),
    uiOutput("vert_dist_hydrText"),
    uiOutput("horiz_dist_roadText"),
    uiOutput("hill_shade_9Text"),
    uiOutput("hill_shade_noonText"),
    uiOutput("hill_shade_3Text"),
    uiOutput("horiz_dist_fireText"),
    uiOutput("wildernessText"),
    uiOutput("soil_typeText"),
    tag("hr",varArgs = ""),
    h4("Based on your input, the predominant tree cover for the forest area will be:"),
    h3(verbatimTextOutput("prediction"))
  )
  
))